### ISSUE TITLE
Merge when 🤖 automerge label is applied, if checks already passed

### ISSUE THREAD

**Issue by encukou** [python/miss-islington#161] opened 2018-09-24 08:49 UTC
I've applied the `🤖 automerge` label to an issue whose checks already passed, and was a bit surprised that nothing happened. I had to press Squash and add `GH-` by hand! (I admit I am very spoiled by useful bots.)

Would it be a good idea automerge when the label is added, if the other conditions are met?

**Comment by Mariatta** [comment] 2018-09-24 08:50
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/python/core-workflow/issues/267 (Automatically apply "needs backport to " labels.), https://github.com/python/miss-islington/issues/131 (Error when trying to merge a PR that's already merged), https://github.com/python/core-workflow/issues/29 (Automatically merge with passing tests and a +1 Review), https://github.com/python/core-workflow/issues/278 (Add 'skip backport' label to skip the backport source check.), and https://github.com/python/core-workflow/issues/27 (Merge commit messages).

**Comment by Mariatta** [comment] 2018-10-12 18:04
The rule is:
- it has `🤖 automerge` label
- it has `awaiting merge` label
- all CI passed

It sounds like the `awaiting merge` label was missing from your PR?

I think having the "awaiting merge" label is important, it signifies that a core developer has approved the PR. If you approved the PR, then it would have automerged.

**Comment by Mariatta** [comment] 2018-11-11 17:09
Closing this issue. The automerge works as intended. I believe it was just missing the "awaiting merge" label in the case you described, which gets added it you approved it.

**Closed by Mariatta** 2018-11-11 17:09 UTC
Labels: enhancement
