### ISSUE TITLE
miss-islington not responding: API rate limit exceeded

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#381] opened 2020-09-04 09:01 UTC
Hi,

The https://github.com/python/cpython/pulls/miss-islington queue is growing. If you look at https://github.com/python/cpython/pull/22076 : the CI tests passed, the PR is approved, but the PR was not merged.

Can someone please have a look? Maybe @Mariatta, @ewdurbin or @brettcannon? I'm not sure who operates this bot.

Victor

**Comment by ewdurbin** [comment] 2020-09-04 09:03
(title edited, pandemic is not a joke)

**Comment by ewdurbin** [comment] 2020-09-04 09:05
Seeing these in logs:

```2020-09-04T09:04:35.021361+00:00 app[web.1]: GH requests remaining: 29/30, reset time: Sep-04-2020 09:05:34 UTC, oauth token length 40, last 4 digits 6bcf, GH delivery ID a621028c-ee8d-11ea-88f9-99507e3589d3 
```

wondering if potentially hitting rate limits.

**Comment by ewdurbin** [comment] 2020-09-04 09:06
it's early :) that's saying we have plenty of requests remaining...

I don't see anything clearly malfunctioning.

**Comment by vstinner** [comment] 2020-09-04 09:58
"API rate limit exceeded": Oh. Can GitHub increase our rate limit?

**Comment by vstinner** [comment] 2020-09-04 09:58
cc @corona10

**Comment by Mariatta** [comment] 2020-09-04 15:16
There's another problem that started since the migration to the new Travis CI https://github.com/python/miss-islington/issues/375

**Comment by Mariatta** [comment] 2020-09-04 17:49
Duplicate of #375

**Closed** 2020-09-04 17:49 UTC
