### ISSUE TITLE
miss-islington broken again

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#228] opened 2019-05-21 10:16 UTC
I don't know what to do when this bot is broken :-(

I requested a backport from master to 3.7 on https://github.com/python/cpython/pull/13421 The bot wrote "Thanks @erikjanss for the PR, and @vstinner for merging it .. I'm working now to backport this PR to: 3.7." and then nothing, as if it fails but doesn't say anything about its failure.

Who operates this bot? Who knows how to debug it?

**Comment by Mariatta** [comment] 2019-05-21 10:34
Sorry of the problem. This is known issue that was raised in https://mail.python.org/pipermail/python-committers/2019-May/006728.html.

Example error log from earlier incident: https://mail.python.org/pipermail/python-committers/2019-May/006729.html

I think one way to fix it is to catch the `redis.exceptions.ConnectionError` and retry the task. Sorry I haven't had time to fix it. I will try adding the fix later today. For now, it seems like there is merge conflict so you'll still need to backport manually 😰

**Comment by vstinner** [comment] 2019-05-21 10:42
> I think one way to fix it is to catch the redis.exceptions.ConnectionError and retry the task.

Well, I cannot say which option is the best. But if the bot fails to produce the PR, would it be possible to add a comment "Sorry, I failed to backport the change: internal error." Something like that?

**Comment by vstinner** [comment] 2019-05-21 10:42
>  For now, it seems like there is merge conflict so you'll still need to backport manually cold_sweat

Oh, that's perfectly fine. I will ask the author to do the backport ;-)

**Comment by matrixise** [comment] 2019-05-21 10:43
just another point, when there is this issue, just add a label "waiting backport" ? it's not a problem to create the backport for the PRs I review.

**Comment by matrixise** [comment] 2019-05-21 11:00
@Mariatta not sure, but I think the issue is mainly with the celery worker and not with your task.

**Comment by matrixise** [comment] 2019-05-21 11:19
I add this issue to the current issue from the kombu project https://github.com/celery/kombu/issues/1019

**Comment by Mariatta** [comment] 2019-05-21 13:30
> just another point, when there is this issue, just add a label "waiting backport" ? it's not a problem to create the backport for the PRs I review.

I don't think we need another label. If miss-islington's backport failed, the "needs backport to ..." label is still there, so we know it is still needs to be backported. In addition, the PR becomes assigned to the core dev who reviews the PR, so core dev also knows they need to do something about it.

**Comment by terryjreedy** [comment] 2019-05-21 18:50
A workaround when no backport appears after, say, 20 minutes, is to remove the backport label and then add it again to trigger the bot again.  I have done this twice and the second try worked both times.

**Closed** 2019-05-22 06:50 UTC

**Comment by Mariatta** [comment] 2019-05-22 06:52
I've made it so it will post a comment that there is problem with backporting because of redis Connection Error. It will also retry the backport up to 5 times (with 60 minutes delay).
