### ISSUE TITLE
A backport must not be merged if a core developer votes -1

### ISSUE THREAD

**Issue by vstinner** [python/miss-islington#111] opened 2018-06-27 10:02 UTC
I approved the https://github.com/python/cpython/pull/7960 but then blocked the PR by voting -1. And... the bot merged the change anyway!

The bot must take also -1 votes from core developers in account...

**Comment by Mariatta** [comment] 2018-06-27 11:02
Sorry about this. I saw you reverted the PR.

This is known problem, but doesn't happen too often. I'll look into fixing this during my office hour this week.

Duplicate of https://github.com/python/miss-islington/issues/62

**Closed** 2018-06-27 11:44 UTC
